from cloudstorageio.interface.drop_box import DropBoxInterface
from cloudstorageio.interface.google_drive import GoogleDriveInterface
from cloudstorageio.interface.google_storage import GoogleStorageInterface
from cloudstorageio.interface.local_storage import LocalStorageInterface
from cloudstorageio.interface.s3 import S3Interface


